/*
  # Fix Resources Table Schema

  ## Changes
  
  1. Drop existing resources table that has incorrect schema
  2. Recreate resources table with correct columns matching the frontend requirements
  3. Insert sample resources data
  
  ## New Schema
  - Includes: type, cost, availability_note, is_example, click_count
  - Removes: city, state, zip, tags, is_crisis_resource
*/

-- Drop existing table
DROP TABLE IF EXISTS resources CASCADE;

-- Create resources table with correct schema
CREATE TABLE resources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text NOT NULL,
  category text NOT NULL,
  type text NOT NULL,
  county text NOT NULL,
  address text DEFAULT '',
  phone text DEFAULT '',
  hours text DEFAULT '',
  website text DEFAULT '',
  languages text[] DEFAULT ARRAY['English'],
  cost text DEFAULT 'Free',
  availability_note text DEFAULT '',
  is_example boolean DEFAULT false,
  click_count integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT valid_category CHECK (category IN (
    'Classes & Workshops',
    'Housing Assistance',
    'Counseling & Support',
    'Legal Services',
    'Parenting Programs',
    'Employment & Education',
    'Food & Basic Needs',
    'Childcare',
    'Transportation',
    'Other'
  )),
  CONSTRAINT valid_cost CHECK (cost IN ('Free', 'Sliding Scale', 'Paid'))
);

-- Create indexes
CREATE INDEX idx_resources_category_county ON resources(category, county);
CREATE INDEX idx_resources_type ON resources(type);

-- Trigger for updated_at
CREATE TRIGGER update_resources_updated_at
  BEFORE UPDATE ON resources
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Enable RLS
ALTER TABLE resources ENABLE ROW LEVEL SECURITY;

-- RLS Policy
CREATE POLICY "Anyone can view resources"
  ON resources FOR SELECT
  TO authenticated
  USING (true);

-- Insert sample resources
INSERT INTO resources (name, description, category, type, county, address, phone, hours, website, languages, cost, is_example) VALUES

('Positive Parenting Program (Triple P)', 
'Evidence-based parenting classes that teach positive parenting strategies. Meets court requirements for parenting education. Topics include managing behavior, communication, and child development.',
'Classes & Workshops',
'Parenting Education',
'Los Angeles',
'1234 Main St, Los Angeles, CA 90012',
'(213) 555-0100',
'Mon-Thu 6:00pm-8:00pm, Sat 10:00am-2:00pm',
'https://example.com/triple-p',
ARRAY['English', 'Spanish'],
'Free',
true),

('Family Therapy Center',
'Individual and family counseling services. Specializes in trauma-informed care and family reunification. Licensed therapists with experience in dependency court cases.',
'Counseling & Support',
'Family Counseling',
'Los Angeles',
'5678 Sunset Blvd, Los Angeles, CA 90028',
'(323) 555-0200',
'Mon-Fri 9:00am-7:00pm, Sat 9:00am-3:00pm',
'https://example.com/family-therapy',
ARRAY['English', 'Spanish', 'Korean'],
'Sliding Scale',
true),

('Housing Rights Center',
'Free assistance finding safe, affordable housing. Help with applications, deposits, and landlord issues. Emergency housing referrals available.',
'Housing Assistance',
'Housing Search',
'Los Angeles',
'910 Fair Housing Ln, Los Angeles, CA 90015',
'(213) 555-0300',
'Mon-Fri 8:00am-5:00pm',
'https://example.com/housing-rights',
ARRAY['English', 'Spanish', 'Vietnamese'],
'Free',
true),

('Public Law Center - Family Defense',
'Free legal help for parents in dependency cases. Can assist with hearings, appeals, and understanding your rights. Attorney consultations available.',
'Legal Services',
'Legal Aid',
'Orange County',
'1111 Justice Way, Santa Ana, CA 92701',
'(714) 555-0400',
'Mon-Fri 9:00am-5:00pm',
'https://example.com/public-law',
ARRAY['English', 'Spanish', 'Vietnamese'],
'Free',
true),

('Substance Abuse Recovery Center',
'Outpatient and intensive outpatient programs. Court-approved substance abuse treatment. Individual and group counseling, relapse prevention, and family support.',
'Counseling & Support',
'Substance Abuse Treatment',
'Orange County',
'2222 Recovery Rd, Anaheim, CA 92805',
'(714) 555-0500',
'Mon-Sun 7:00am-9:00pm',
'https://example.com/recovery',
ARRAY['English', 'Spanish'],
'Sliding Scale',
true),

('Domestic Violence Support Services',
'Confidential support for survivors of domestic violence. Safety planning, counseling, legal advocacy, and emergency shelter referrals. 24/7 crisis line available.',
'Counseling & Support',
'Domestic Violence Services',
'San Diego',
'3333 Safe Harbor Dr, San Diego, CA 92101',
'(619) 555-0600',
'24/7 Crisis Line, Office Hours: Mon-Fri 9:00am-5:00pm',
'https://example.com/dv-support',
ARRAY['English', 'Spanish', 'Tagalog'],
'Free',
true),

('Parent Partner Program',
'Mentorship from parents who have successfully navigated the dependency court system. One-on-one support, court accompaniment, and resource navigation.',
'Parenting Programs',
'Peer Support',
'San Diego',
'4444 Hope St, San Diego, CA 92110',
'(619) 555-0700',
'By Appointment, Mon-Sat 8:00am-8:00pm',
'https://example.com/parent-partner',
ARRAY['English', 'Spanish'],
'Free',
true),

('WorkSource California',
'Job training, resume help, interview preparation, and job placement services. Computer classes and GED preparation also available.',
'Employment & Education',
'Job Training',
'Sacramento',
'5555 Career Blvd, Sacramento, CA 95814',
'(916) 555-0800',
'Mon-Fri 8:00am-5:00pm',
'https://example.com/worksource',
ARRAY['English', 'Spanish', 'Russian'],
'Free',
true),

('Family Preservation Services',
'In-home support services to help families stay together. Case management, parenting coaching, life skills training, and connection to community resources.',
'Parenting Programs',
'In-Home Services',
'Sacramento',
'6666 Family Way, Sacramento, CA 95825',
'(916) 555-0900',
'Mon-Fri 8:00am-6:00pm, Emergency On-Call 24/7',
'https://example.com/family-preservation',
ARRAY['English', 'Spanish', 'Hmong'],
'Free',
true),

('Anger Management Workshops',
'Court-approved anger management classes. Learn coping strategies, communication skills, and stress management. Individual and group sessions available.',
'Classes & Workshops',
'Anger Management',
'Los Angeles',
'7777 Peace St, Los Angeles, CA 90017',
'(213) 555-1000',
'Tue & Thu 6:00pm-8:00pm, Sat 10:00am-12:00pm',
'https://example.com/anger-management',
ARRAY['English', 'Spanish'],
'Sliding Scale',
true),

('Community Food Bank',
'Free groceries and hot meals. No appointment needed. CalFresh application assistance available.',
'Food & Basic Needs',
'Food Assistance',
'Los Angeles',
'8888 Harvest Ave, Los Angeles, CA 90021',
'(213) 555-1100',
'Mon, Wed, Fri 9:00am-2:00pm',
'https://example.com/food-bank',
ARRAY['English', 'Spanish', 'Armenian'],
'Free',
true),

('Safe Rides Transportation Program',
'Free transportation to court hearings, visitations, and service appointments. Must schedule 48 hours in advance.',
'Transportation',
'Court & Service Transportation',
'Orange County',
'9999 Transit Way, Santa Ana, CA 92704',
'(714) 555-1200',
'Mon-Sat 7:00am-7:00pm',
'https://example.com/safe-rides',
ARRAY['English', 'Spanish'],
'Free',
true),

('Napa-Solano Parenting Classes',
'Weekly parenting classes covering child development, discipline, and communication. Certificate of completion provided for court.',
'Classes & Workshops',
'Parenting Education',
'Contra Costa',
'101 Parent Ave, Martinez, CA 94553',
'(925) 555-1300',
'Wed 6:00pm-8:00pm',
'https://example.com/napa-solano-parenting',
ARRAY['English', 'Spanish'],
'Free',
true),

('Central Valley Housing Initiative',
'Rental assistance, deposit help, and landlord mediation. Case managers help families find and maintain stable housing.',
'Housing Assistance',
'Housing Search',
'Fresno',
'2020 Housing Blvd, Fresno, CA 93721',
'(559) 555-1400',
'Mon-Fri 9:00am-5:00pm',
'https://example.com/central-valley-housing',
ARRAY['English', 'Spanish', 'Punjabi'],
'Free',
true),

('Valley Counseling Center',
'Licensed therapists providing individual, family, and group therapy. Specializes in trauma, substance abuse, and co-parenting support.',
'Counseling & Support',
'Family Counseling',
'Kern',
'3030 Therapy Way, Bakersfield, CA 93301',
'(661) 555-1500',
'Mon-Sat 8:00am-8:00pm',
'https://example.com/valley-counseling',
ARRAY['English', 'Spanish'],
'Sliding Scale',
true),

('Inland Empire Legal Services',
'Free legal consultations for dependency court cases. Help with paperwork, court preparation, and understanding your rights.',
'Legal Services',
'Legal Aid',
'Riverside',
'4040 Justice Pkwy, Riverside, CA 92501',
'(951) 555-1600',
'Mon-Fri 9:00am-5:00pm, Thu evening hours',
'https://example.com/inland-legal',
ARRAY['English', 'Spanish'],
'Free',
true),

('Bay Area Family Support',
'Parent coaching, supervised visitation, and family therapy. Helps families work toward reunification goals.',
'Parenting Programs',
'Family Support Services',
'Alameda',
'5050 Family Circle, Oakland, CA 94612',
'(510) 555-1700',
'Mon-Fri 8:00am-6:00pm, Sat 9:00am-1:00pm',
'https://example.com/bay-area-family',
ARRAY['English', 'Spanish', 'Cantonese'],
'Sliding Scale',
true),

('Silicon Valley Job Center',
'Employment services including resume building, job search assistance, and interview coaching. Computer lab and skills training available.',
'Employment & Education',
'Job Training',
'Santa Clara',
'6060 Career Center Dr, San Jose, CA 95110',
'(408) 555-1800',
'Mon-Fri 8:00am-5:00pm',
'https://example.com/sj-job-center',
ARRAY['English', 'Spanish', 'Vietnamese'],
'Free',
true),

('North County Parenting Circle',
'Peer support groups for parents in dependency court. Share experiences, get support, learn from others who understand your journey.',
'Parenting Programs',
'Peer Support',
'Ventura',
'7070 Support St, Ventura, CA 93001',
'(805) 555-1900',
'Thu 6:00pm-8:00pm',
'https://example.com/north-county-parenting',
ARRAY['English', 'Spanish'],
'Free',
true),

('Central Coast Transportation Services',
'Free rides to court, visitations, and service appointments. Wheelchair accessible vehicles available.',
'Transportation',
'Court & Service Transportation',
'San Joaquin',
'8080 Transit Ave, Stockton, CA 95202',
'(209) 555-2000',
'Mon-Sat 6:00am-8:00pm',
'https://example.com/central-coast-transport',
ARRAY['English', 'Spanish', 'Tagalog'],
'Free',
true),

('Community Food Pantry Network',
'Weekly food distribution, hot meals, and nutrition education. CalFresh enrollment assistance available.',
'Food & Basic Needs',
'Food Assistance',
'Stanislaus',
'9090 Food Bank Rd, Modesto, CA 95350',
'(209) 555-2100',
'Tue & Thu 10:00am-2:00pm, Sat 9:00am-12:00pm',
'https://example.com/food-pantry-network',
ARRAY['English', 'Spanish'],
'Free',
true),

('SF Family Law Project',
'Pro bono legal representation for low-income families in dependency court. Full representation and legal advice.',
'Legal Services',
'Legal Aid',
'San Francisco',
'1010 Legal Plaza, San Francisco, CA 94102',
'(415) 555-2200',
'Mon-Fri 9:00am-5:00pm',
'https://example.com/sf-family-law',
ARRAY['English', 'Spanish', 'Chinese'],
'Free',
true),

('East Bay Substance Recovery',
'Outpatient treatment, group therapy, and relapse prevention. Court-approved program with flexible scheduling.',
'Counseling & Support',
'Substance Abuse Treatment',
'Alameda',
'1111 Recovery Blvd, Berkeley, CA 94704',
'(510) 555-2300',
'Mon-Sun 6:00am-10:00pm',
'https://example.com/east-bay-recovery',
ARRAY['English', 'Spanish'],
'Sliding Scale',
true),

('Peninsula Child Care Resource Center',
'Help finding affordable, quality childcare. Subsidies available for eligible families. Referrals to licensed providers.',
'Childcare',
'Childcare Assistance',
'San Bernardino',
'1212 Childcare Way, San Bernardino, CA 92401',
'(909) 555-2400',
'Mon-Fri 8:00am-5:00pm',
'https://example.com/peninsula-childcare',
ARRAY['English', 'Spanish'],
'Sliding Scale',
true),

('Life Skills Academy',
'Classes in budgeting, cooking, time management, and household organization. Certificate programs available.',
'Classes & Workshops',
'Life Skills Training',
'Sacramento',
'1313 Skills Center, Sacramento, CA 95814',
'(916) 555-2500',
'Mon, Wed, Fri 6:00pm-8:00pm',
'https://example.com/life-skills-academy',
ARRAY['English', 'Spanish', 'Hmong'],
'Free',
true);
